import Head from 'next/head'
import React from 'react'
import { useRouter } from 'next/router'
import { MainLayout } from '../layouts/main.layout'

const ArticlePage = (): JSX.Element => {
  const router = useRouter()
  const { slug } = router.query

  return (
    <main>
      <h2> article page {slug}</h2>
    </main>
  )
}

ArticlePage.getLayout = function getLayout(page: React.ReactElement) {
  return (
    <>
      <Head>
        <title>Wiki Client</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>{page}</MainLayout>
    </>
  )
}

export default ArticlePage
