import { Box, Divider, Typography } from '@mui/material'
import Head from 'next/head'
import React from 'react'
import { ReactElement } from 'react'
import ReactMarkdown from 'react-markdown'
import { useQuery } from 'react-query'
import remarkGfm from 'remark-gfm'
import styled from 'styled-components'
import { IArticle } from '../interfaces/Article'
import { MainLayout } from '../layouts/main.layout'
import articleService from '../services/article.service'
import type { NextPageWithLayout } from './_app'

const ArticleWrapper = styled.main({
  padding: '15px',
})

const Home: NextPageWithLayout = () => {
  const {
    data: article,
    isError,
    error,
  } = useQuery<IArticle>(
    ['firstArticle'],
    async () => await articleService.getFirst(),
    { staleTime: 1000 * 5 }
  )
  if (!article) return <div>no data...</div>
  if (isError)
    return (
      <div>
        <>Error: {error}</>{' '}
      </div>
    )

  return (
    <>
      <Head>
        <title>{article.title}</title>
      </Head>
      <ArticleWrapper>
        <Typography
          variant="h4"
          gutterBottom
          component="div"
          textAlign="center"
          sx={{ paddingTop: '20px' }}
        >
          {article.title}
        </Typography>
        <Divider />
        <Box sx={{ maxWidth: '900px', overflowX: 'hidden' }}>
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {article.content}
          </ReactMarkdown>
        </Box>
      </ArticleWrapper>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <Head>
        <title>Wiki Client</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>{page}</MainLayout>
    </>
  )
}

export default Home
